ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}-slim
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements_py2.txt
RUN pip install black
CMD ["black", "--version"]
COPY vobject /app/vobject
COPY ./tests.py /app/tests.py
