ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}-slim
WORKDIR /app
RUN apt-get update && apt-get install -y git

RUN pip install --upgrade pip
RUN pip install pre-commit

COPY ./scripts/checks.sh /app/checks.sh

CMD ["./checks.sh"]
